name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug] "
labels: ["bug-report"]
body:
  - type: input
    attributes:
      label: RT-Thread Version
      description: |
        Which version/branch/git-hash of RT-Thread are you using?
    validations:
      required: true

  - type: input
    attributes:
      label: Hardware Type/Architectures
      description: Specify your Hardware/BSP model.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Develop Toolchain
      description: which toolchain are you using?
      options:
        - Other
        - RT-Thread Studio
        - Microsoft VScode
        - MDK Keil
        - IAR
        - GCC
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug.
      placeholder: |
        1. Steps to reproduce the behavior
        2. Expected behavior
        3. Add screenshot / media if you have them
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other additional context
      description: Add any other context about the problem here.
